# Generated by Django 2.2.17 on 2021-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieapp', '0002_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
