# Generated by Django 2.2.17 on 2021-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieapp', '0002_auto_20210406_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
