# Generated by Django 2.2.17 on 2021-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieapp', '0004_auto_20210406_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=40), unique=True),
        ),
    ]
